/** Salary slip — printable paper and preview modal. "Download PDF" = print → Save as PDF. */
import { Download, Printer, Send } from 'lucide-react'
import { useErp } from '../../store/ErpStore.jsx'
import { monthTitle } from '../../store/hr.js'
import { amountInWords, fmtDate, inr2 } from '../../utils/format.js'
import { printPage } from '../../utils/export.js'
import { Button, Modal, useToast } from '../../components/ui/index.js'
import BrandMark from '../../components/layout/BrandMark.jsx'

export function PayslipPaper({ run, slip }) {
  const { state } = useErp()
  const c = state.settings.company
  const emp = (state.employees || []).find((e) => e.id === slip.employeeId) || {}
  const a = slip.attendance
  const rows = Math.max(slip.earnings.length, slip.deductions.length)
  return (
    <div className="doc-paper print-area">
      <div className="doc-head">
        <div className="row" style={{ alignItems: 'flex-start', gap: 12 }}>
          {c.logo ? <img src={c.logo} alt="" style={{ width: 48, height: 48, objectFit: 'contain' }} /> : <BrandMark size={44} />}
          <div>
            <div className="doc-company-name">{c.name}</div>
            <div className="doc-company-meta">
              {c.legalName}
              <br />
              {c.address}, {c.city}, {c.state} {c.pincode}
            </div>
          </div>
        </div>
        <div className="doc-type">
          <div className="doc-type-title">Salary Slip</div>
          <div className="doc-type-sub">{monthTitle(run.month)}</div>
          {run.status === 'Paid' && (
            <div style={{ marginTop: 10 }}>
              <span className="doc-stamp">PAID</span>
            </div>
          )}
        </div>
      </div>

      <dl className="slip-grid">
        <div><dt>Employee</dt><dd>{slip.name}</dd></div>
        <div><dt>Employee code</dt><dd>{slip.code}</dd></div>
        <div><dt>Designation</dt><dd>{slip.designation}</dd></div>
        <div><dt>Department</dt><dd>{slip.department}</dd></div>
        <div><dt>Date of joining</dt><dd>{fmtDate(emp.joiningDate)}</dd></div>
        <div><dt>PAN</dt><dd>{emp.pan || '—'}</dd></div>
        <div><dt>UAN</dt><dd>{emp.uan || '—'}</dd></div>
        <div><dt>ESIC no.</dt><dd>{emp.esicNo || '—'}</dd></div>
        <div><dt>Salary type</dt><dd>{slip.salaryType === 'Daily' ? `Daily wage, ${inr2(slip.rate)}/day` : `Monthly, ${inr2(slip.rate)}`}</dd></div>
        <div><dt>Paid by</dt><dd>{slip.bank ? `${slip.bank.bankName}, A/c ${slip.bank.account}` : 'Cash'}</dd></div>
        <div><dt>Paid days</dt><dd>{slip.paidDays} of {slip.days}</dd></div>
        <div><dt>Loss of pay days</dt><dd>{slip.lopDays}</dd></div>
      </dl>

      <div className="slip-att">
        <span>Present <b>{a.present}</b></span>
        <span>Half days <b>{a.halfDay}</b></span>
        <span>Paid leave <b>{a.leavePaid}</b></span>
        <span>Unpaid leave <b>{a.leaveUnpaid}</b></span>
        <span>Absent <b>{a.absent}</b></span>
        <span>Weekly offs <b>{a.weeklyOff}</b></span>
        <span>Holidays <b>{a.holidays}</b></span>
        <span>Overtime <b>{a.otHours} h</b></span>
      </div>

      <div className="slip-money">
        <div>
          <h4>Earnings</h4>
          {Array.from({ length: rows }, (_, i) => slip.earnings[i]).map((e, i) => (
            <div key={e?.key || `e${i}`} className="ln"><span>{e?.label || ' '}</span><span>{e ? inr2(e.amount) : ''}</span></div>
          ))}
          <div className="ln tot"><span>Gross earnings</span><span>{inr2(slip.gross)}</span></div>
        </div>
        <div>
          <h4>Deductions</h4>
          {Array.from({ length: rows }, (_, i) => slip.deductions[i]).map((d, i) => (
            <div key={d?.key || `d${i}`} className="ln"><span>{d?.label || ' '}</span><span>{d ? inr2(d.amount) : ''}</span></div>
          ))}
          <div className="ln tot"><span>Total deductions</span><span>{inr2(slip.totalDeductions)}</span></div>
        </div>
      </div>

      <div className="slip-net">
        <div>
          <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.06em' }}>Net pay</div>
          <div className="words">{amountInWords(slip.netPay)}</div>
        </div>
        <div className="amt">{inr2(slip.netPay)}</div>
      </div>

      <div className="doc-foot">
        <div className="doc-terms">
          Employer contribution (not part of net pay): PF {inr2(slip.employerPf)}, ESI {inr2(slip.employerEsi)}.
          <br />
          Salary sheet {run.number}{run.paidOn ? `, paid on ${fmtDate(run.paidOn)}` : ''}.
        </div>
        <div className="doc-sign">
          <div style={{ fontWeight: 600 }}>For {c.name}</div>
          <div className="sign-line">Authorised Signatory</div>
        </div>
      </div>
      <div className="doc-footer-note">This is a computer-generated salary slip. Generated by NexttGen ERP (demo).</div>
    </div>
  )
}

export default function PayslipModal({ run, slip, onClose }) {
  const toast = useToast()
  return (
    <Modal
      open={Boolean(slip)}
      onClose={onClose}
      size="xl"
      title="Salary slip"
      subtitle={slip ? `${slip.name}, ${monthTitle(run.month)}` : ''}
      footer={
        <>
          <Button variant="ghost" onClick={onClose} style={{ marginRight: 'auto' }}>Close</Button>
          <Button icon={Send} onClick={() => toast.success('Sent (demo)', `${slip.name}’s salary slip would be shared on WhatsApp and email in the live product.`)}>Send to employee</Button>
          <Button icon={Download} onClick={() => { toast.info('Download PDF', 'Choose “Save as PDF” as the destination in the print dialog.'); printPage() }}>Download PDF</Button>
          <Button variant="primary" icon={Printer} onClick={printPage}>Print</Button>
        </>
      }
    >
      {slip && <PayslipPaper run={run} slip={slip} />}
    </Modal>
  )
}
